/**
 * ========================================
 * MÓDULO DE VISTAS - Navegación y Datos
 * ========================================
 * Propósito: Gestiona la navegación entre vistas y carga de datos del usuario
 * 
 * Funcionalidades:
 * - Carga inicial de datos del usuario (favoritos, historial, playlists automáticas)
 * - Navegación entre vistas (home, búsqueda, biblioteca, artista, álbum)
 * - Vista de artista con top tracks y discografía
 * - Vista de álbum con lista de canciones
 * - Vista de canciones favoritas
 * - Gestión del historial de navegación
 * 
 * Exports:
 * - loadUserData: Carga datos del usuario al iniciar
 * - setupInitialDataLoad: Configura carga inicial
 * - openArtistPage: Abre página de artista
 * - openAlbumView: Abre vista de álbum
 * - openLikedSongsView: Abre vista de favoritos
 */
(function () {
    function createViewsModule(config) {
        const {
            state,
            deps,
        } = config;

        const {
            artistParam,
            resultsDiv,
            loadingDiv,
            errorDiv,
            readJsonResponse,
            formatDuration,
            fetchImpl,
            showSearchView,
            showHomeView,
            populateHomeCards,
            prefetchSongs,
            setQueueAndPlayFromSongs,
            toggleLikeSong,
            loadPlaylists,
            saveMadeForYouPlaylists,
            saveLikedSongs,
            saveLikedSongsPlaylist,
            updateLikeButton,
            fetchRecentlyPlayed,
            fetchLikedSongs,
            fetchAutoGeneratedPlaylists,
            buildSongActions,
        } = deps;

        let albumPrevResults = '';  // Guarda los resultados anteriores de búsqueda de álbum

        /**
         * Carga los datos iniciales del usuario desde el servidor
         * - Historial de reproducción reciente
         * - Canciones favoritas
         * - Playlists automáticas
         * 
         * Esta función se ejecuta al iniciar la aplicación
         */
        async function loadUserData() {
            try {
                // ─── Carga Historial de Reproducción ───
                const recent = await fetchRecentlyPlayed();
                state.setRecentlyPlayed((recent || []).map(r => ({
                    id: r.id ?? r.song_id ?? '',
                    title: r.title ?? r.song_title ?? 'Cancion desconocida',
                    author: r.author ?? r.song_author ?? 'Desconocido',
                    duration: r.duration ?? r.song_duration ?? 0,
                    thumbnail: (r.thumbnail ?? r.song_thumbnail ?? '') || '',
                    played_at: r.played_at ?? r.playedAt ?? '',
                })));

                // Pre-carga las canciones recientes en segundo plano
                prefetchSongs(state.getRecentlyPlayed());

                // ─── Carga Canciones Favoritas ───
                const likedRaw = await fetchLikedSongs();
                if (Array.isArray(likedRaw) && likedRaw.length > 0) {
                    const likedObjects = likedRaw.map(r => ({
                        id: r.song_id ?? r.id ?? '',
                        title: r.song_title ?? r.title ?? 'Cancion desconocida',
                        author: r.song_author ?? r.author ?? 'Desconocido',
                        duration: r.song_duration ?? r.duration ?? 0,
                        thumbnail: (r.song_thumbnail ?? r.thumbnail ?? '') || '',
                    })).filter(s => s.id);
                    saveLikedSongsPlaylist(likedObjects);
                    state.setLikedSongs(likedObjects.map(s => s.id));
                    saveLikedSongs();
                } else {
                    // Si no hay favoritos, inicializa vacío
                    saveLikedSongsPlaylist([]);
                    state.setLikedSongs([]);
                    saveLikedSongs();
                }

                // ─── Carga Playlists Automáticas ───
                const autoPlaylists = await fetchAutoGeneratedPlaylists();
                const validAutoPlaylists = autoPlaylists.filter(p => Array.isArray(p.songs) && p.songs.length > 0);
                if (validAutoPlaylists.length > 0) {
                    saveMadeForYouPlaylists(validAutoPlaylists);
                }

                // Actualiza el botón de like si hay una canción reproduciéndose
                if (state.getCurrentSong()) {
                    updateLikeButton();
                }
            } catch (error) {
                console.error('Error loading user data:', error);
                // En caso de error, inicializa vacío
                state.setLikedSongs([]);
                state.setRecentlyPlayed([]);
            }
        }

        /**
         * Configura la carga inicial de datos cuando el DOM está listo
         * - Si hay parámetro 'artist' en la URL, carga la página del artista
         * - Carga los datos del usuario
         * - Muestra la vista home
         */
        function setupInitialDataLoad() {
            document.addEventListener('DOMContentLoaded', async () => {
                // Si hay un artista en la URL, carga su página
                if (artistParam) {
                    loadArtistPage(artistParam);
                }
                await loadUserData();
                populateHomeCards();
            });
        }

        /**
         * Abre la página de un artista
         * @param {string} artistName - Nombre del artista
         */
        function openArtistPage(artistName) {
            if (!artistName) return;
            loadArtistPage(artistName);
        }

        /**
         * Abre la vista de un álbum
         * @param {string} playlistId - ID del álbum/playlist
         * @param {string} title - Título del álbum
         * @param {string} thumbnail - URL de la portada
         */
        async function openAlbumView(playlistId, title, thumbnail) {
            if (!playlistId) return;
            window._isSearchPlaylist = false;  // Flag para indicar que no es una búsqueda

            // Detectar desde qué vista se abre el álbum para que el botón volver funcione bien
            const _homeViewEl = document.getElementById('homeView');
            const _plViewEl   = document.getElementById('playlistView');
            if (_homeViewEl && _homeViewEl.style.display === 'block') {
                window._albumOriginView = 'home';
            } else if (_plViewEl && _plViewEl.style.display === 'block') {
                window._albumOriginView = 'playlist';
            } else {
                window._albumOriginView = 'search';
            }

            showSearchView();
            const genreTiles = document.getElementById('genreTiles');
            if (genreTiles) genreTiles.style.display = 'none';

            albumPrevResults = resultsDiv.innerHTML;
            loadingDiv.style.display = 'flex';
            errorDiv.style.display = 'none';
            resultsDiv.innerHTML = '';

            try {
                const res = await fetchImpl(`/album?id=${encodeURIComponent(playlistId)}`);
                const { data, raw } = await readJsonResponse(res);
                if (!res.ok) throw new Error((data && data.error) || raw || `HTTP ${res.status}`);
                if (!data) throw new Error('Respuesta invalida del servidor');
                if (data.error) throw new Error(data.error);
                displayAlbumView(data, thumbnail);
            } catch (err) {
                errorDiv.textContent = 'Error cargando el album: ' + err.message;
                errorDiv.style.display = 'block';
            } finally {
                loadingDiv.style.display = 'none';
            }
        }

        /**
         * Muestra la vista de un álbum o playlist con su lista de canciones
         * Renderiza:
         * - Portada y metadatos del álbum
         * - Botón para reproducir todo
         * - Botón para guardar como playlist
         * - Lista de canciones con duración
         * @param {Object} albumData - Datos del álbum {title, author, trackCount, tracks}
         * @param {string} fallbackThumb - Portada alternativa si no existe
         */
        function displayAlbumView(albumData, fallbackThumb) {
            const safeFallbackThumb = fallbackThumb || '';
            const { title, author, trackCount, tracks } = albumData;
            const thumb = safeFallbackThumb || albumData.thumbnail || (tracks[0]?.thumbnail) || '';

            const wrap = document.createElement('div');
            wrap.className = 'album-view';
            wrap.innerHTML = `
                <div class="album-header">
                    <button class="album-back-btn" id="albumBackBtn" aria-label="Volver">
                        <svg viewBox="0 0 24 24" width="20" height="20"><path fill="currentColor" d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z"/></svg>
                    </button>
                    <div class="album-header-body">
                        <img class="album-header-img" src="${thumb}" alt="${title}">
                        <div class="album-header-info">
                            <p class="album-header-type">Lista de reproduccion</p>
                            <h1 class="album-header-title">${title}</h1>
                            <p class="album-header-meta">${author || ''} &nbsp;.&nbsp; ${trackCount} canciones</p>
                        </div>
                    </div>
                </div>
                <div class="album-control-bar">
                    <button class="play-all-btn" id="albumPlayAllBtn" aria-label="Reproducir todo">
                        <svg viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M8 5v14l11-7z"/></svg>
                    </button>
                    <button class="album-save-btn" id="albumSaveBtn" aria-label="Guardar como playlist">
                        <svg viewBox="0 0 24 24" width="18" height="18"><path fill="currentColor" d="M17 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V7l-4-4zm-5 16c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3zm3-10H5V5h10v4z"/></svg>
                        Guardar como playlist
                    </button>
                    <span class="album-save-msg" id="albumSaveMsg"></span>
                </div>
                <div class="album-track-list" id="albumTrackList"></div>
            `;

            wrap.querySelector('#albumBackBtn').addEventListener('click', () => {
                resultsDiv.innerHTML = '';
                const prev = albumPrevResults;
                albumPrevResults = '';
                if (window._albumOriginView === 'home') {
                    showHomeView();
                    return;
                }
                if (window._albumOriginView === 'playlist') {
                    document.getElementById('searchView').style.display = 'none';
                    document.getElementById('playlistView').style.display = 'block';
                    return;
                }

                resultsDiv.innerHTML = prev;
                resultsDiv.querySelectorAll('.album-card').forEach(card => {
                    const playBtn = card.querySelector('.album-card-play');
                    const albumId = card.dataset.albumId;
                    const albumTitle = card.dataset.albumTitle;
                    const albumThumb = card.dataset.albumThumb;
                    if (!albumId) return;
                    playBtn?.addEventListener('click', (e) => {
                        e.stopPropagation();
                        openAlbumView(albumId, albumTitle, albumThumb);
                    });
                    card.addEventListener('click', () => openAlbumView(albumId, albumTitle, albumThumb));
                });
            });

            wrap.querySelector('#albumSaveBtn').addEventListener('click', async () => {
                const token = localStorage.getItem('token');
                if (!token) {
                    alert('Debes iniciar sesion para guardar playlists.');
                    return;
                }

                const saveBtn = wrap.querySelector('#albumSaveBtn');
                const saveMsg = wrap.querySelector('#albumSaveMsg');
                saveBtn.disabled = true;
                saveBtn.textContent = 'Guardando...';
                saveMsg.textContent = '';

                try {
                    const createRes = await fetchImpl('/create-playlist', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                        body: JSON.stringify({ name: title }),
                    });
                    const { data: createData, raw: createRaw } = await readJsonResponse(createRes);
                    if (!createRes.ok) {
                        throw new Error((createData && (createData.error || createData.message)) || createRaw || `HTTP ${createRes.status}`);
                    }
                    if (!createData) throw new Error('Respuesta invalida al crear playlist');
                    if (!createData.success) throw new Error(createData.error || 'No se pudo crear la playlist');

                    const playlistId = createData.playlist.id;
                    for (const song of tracks) {
                        const addRes = await fetchImpl('/add-to-playlist', {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                            body: JSON.stringify({
                                playlist_id: playlistId,
                                song: { id: song.id, title: song.title, author: song.author, duration: song.duration, thumbnail: song.thumbnail },
                            }),
                        });
                        if (!addRes.ok) {
                            const { data: addData, raw: addRaw } = await readJsonResponse(addRes);
                            throw new Error((addData && (addData.error || addData.message)) || addRaw || `HTTP ${addRes.status}`);
                        }
                    }

                    saveMsg.textContent = 'Guardado en tu biblioteca';
                    saveMsg.style.color = '#1DB954';
                    saveBtn.innerHTML = '<svg viewBox="0 0 24 24" width="18" height="18"><path fill="currentColor" d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z"/></svg> Guardado';
                    loadPlaylists();
                } catch (err) {
                    saveMsg.textContent = 'Error: ' + err.message;
                    saveMsg.style.color = '#f15e6c';
                    saveBtn.disabled = false;
                    saveBtn.innerHTML = '<svg viewBox="0 0 24 24" width="18" height="18"><path fill="currentColor" d="M17 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V7l-4-4zm-5 16c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3zm3-10H5V5h10v4z"/></svg> Guardar';
                }
            });

            const listEl = wrap.querySelector('#albumTrackList');
            tracks.forEach((song, i) => {
                const row = document.createElement('div');
                row.className = 'album-track-row';
                row.dataset.index = i;
                row.innerHTML = `
                    <div class="album-track-num">
                        <span class="album-track-n">${i + 1}</span>
                        <svg class="album-track-play-icon" viewBox="0 0 24 24" width="16" height="16"><path fill="currentColor" d="M8 5v14l11-7z"/></svg>
                    </div>
                    <img src="${song.thumbnail}" alt="${song.title}" class="album-track-thumb">
                    <div class="album-track-info">
                        <div class="album-track-title">${song.title}</div>
                        <div class="album-track-artist">${song.author}</div>
                    </div>
                    <span class="album-track-dur">${formatDuration(song.duration)}</span>
                `;
                // Botón de 3 puntos - Bug B fix
                const dotsBtn = document.createElement('button');
                dotsBtn.className = 'album-track-dots';
                dotsBtn.title = 'Más opciones';
                dotsBtn.innerHTML = `<svg viewBox="0 0 24 24" width="18" height="18"><circle cx="12" cy="5" r="1.5" fill="currentColor"/><circle cx="12" cy="12" r="1.5" fill="currentColor"/><circle cx="12" cy="19" r="1.5" fill="currentColor"/></svg>`;
                dotsBtn.addEventListener('click', (e) => {
                    e.stopPropagation();
                    if (typeof window._showSongContextMenu === 'function') {
                        window._showSongContextMenu(e, song);
                    }
                });
                row.appendChild(dotsBtn);
                row.addEventListener('click', () => setQueueAndPlayFromSongs(tracks, song));
                listEl.appendChild(row);
            });

            wrap.querySelector('#albumPlayAllBtn').addEventListener('click', () => {
                setQueueAndPlayFromSongs(tracks, tracks[0]);
            });

            resultsDiv.appendChild(wrap);
            const mainContent = document.querySelector('.main-content');
            if (mainContent) mainContent.scrollTop = 0;
            prefetchSongs(tracks);
        }

        /**
         * Carga la página completa de un artista desde el servidor
         * Realiza petición al endpoint /artist y muestra los datos
         * @param {string} artistName - Nombre del artista a cargar
         */
        async function loadArtistPage(artistName) {
            window._isSearchPlaylist = false;  // Flag para indicar que no es una búsqueda
            try {
                loadingDiv.style.display = 'block';
                errorDiv.style.display = 'none';
                resultsDiv.innerHTML = '';

                // Petición al servidor para obtener datos del artista
                const response = await fetchImpl(`/artist?name=${encodeURIComponent(artistName)}`);
                const artistData = await response.json();
                if (artistData.error) {
                    throw new Error(artistData.error);
                }
                displayArtistProfile(artistData);
            } catch (err) {
                errorDiv.textContent = 'Error cargando perfil del artista: ' + err.message;
                errorDiv.style.display = 'block';
            } finally {
                loadingDiv.style.display = 'none';
            }
        }

        /**
         * Renderiza el perfil completo de un artista
         * Muestra:
         * - Banner con imagen de fondo
         * - Badge de "Artista verificado"
         * - Nombre y oyentes mensuales (calculados)
         * - Botón de reproducir todo
         * - Botón de seguir
         * - Lista de top tracks y discografía
         * @param {Object} artistData - Objeto con {artist: nombre, songs: array}
         */
        function displayArtistProfile(artistData) {
            const { artist, songs } = artistData;
            const listenersApprox = (songs.length * 847 + 12300).toLocaleString();
            const coverImg = songs.length > 0 ? songs[0].thumbnail : '';

            const profileEl = document.createElement('div');
            profileEl.className = 'artist-profile';
            profileEl.innerHTML = `
                <div class="artist-header-large" style="background-image:url('${coverImg}')">
                    <div class="artist-header-overlay"></div>
                    <div class="artist-header-content">
                        <div class="artist-verified">
                            <svg viewBox="0 0 24 24" width="20" height="20">
                                <path fill="#5c67f2" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 14.5v-9l6 4.5-6 4.5z"/>
                            </svg>
                            Artista verificado
                        </div>
                        <h1 class="artist-name-large">${artist}</h1>
                        <p class="artist-listeners">${listenersApprox} oyentes mensuales</p>
                    </div>
                </div>

                <div class="artist-control-bar">
                    <button class="play-all-btn" id="artistPlayAllBtn" aria-label="Reproducir">
                        <svg viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M8 5v14l11-7z"/></svg>
                    </button>
                    <button class="artist-action-btn" id="artistFollowBtn">Seguir</button>
                    <button class="artist-options-btn" aria-label="Mas opciones">
                        <svg viewBox="0 0 24 24" width="20" height="20">
                            <circle cx="12" cy="5" r="1.5" fill="currentColor"/>
                            <circle cx="12" cy="12" r="1.5" fill="currentColor"/>
                            <circle cx="12" cy="19" r="1.5" fill="currentColor"/>
                        </svg>
                    </button>
                </div>

                <div class="artist-popular-section">
                    <h2>Populares</h2>
                    <div class="popular-list" id="artistSongList"></div>
                    <button class="artist-see-more" id="artistSeeMore">VER MAS</button>
                </div>
            `;

            const listEl = profileEl.querySelector('#artistSongList');
            const sortedSongs = [...songs].sort((a, b) => (b.viewCount ?? 0) - (a.viewCount ?? 0));
            let showAll = false;
            const maxInitial = 5;

            function renderSongs() {
                listEl.innerHTML = '';
                const toShow = showAll ? sortedSongs : sortedSongs.slice(0, maxInitial);
                toShow.forEach((song, index) => {
                    const liked = state.getLikedSongs().includes(song.id);
                    const row = document.createElement('div');
                    row.className = 'artist-song-row';
                    row.dataset.index = index;
                    row.innerHTML = `
                        <div class="song-row-num">${index + 1}</div>
                        <div class="song-row-play">
                            <svg viewBox="0 0 24 24" width="16" height="16"><path fill="currentColor" d="M8 5v14l11-7z"/></svg>
                        </div>
                        <img src="${song.thumbnail}" alt="${song.title}" class="song-row-thumb">
                        <div class="song-row-info">
                            <div class="song-row-title">${song.title}</div>
                            <div class="song-row-artist">${song.author ?? artist}</div>
                        </div>
                        <button class="song-row-like${liked ? ' liked' : ''}" data-song-id="${song.id}" aria-label="Me gusta">
                            <svg viewBox="0 0 24 24" width="14" height="14">
                                ${liked
                                    ? '<path fill="#1DB954" d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>'
                                    : '<path fill="currentColor" d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z"/>'}
                            </svg>
                        </button>
                        <div class="song-row-duration">${formatDuration(song.duration)}</div>
                    `;
                    row.querySelector('.song-row-like').addEventListener('click', (e) => {
                        e.stopPropagation();
                        toggleLikeSong(song);
                        renderSongs();
                    });
                    row.addEventListener('click', (e) => {
                        if (e.target.closest('.song-actions')) return;
                        setQueueAndPlayFromSongs(sortedSongs, song);
                    });
                    if (typeof buildSongActions === 'function') {
                        row.appendChild(buildSongActions(song));
                    }
                    listEl.appendChild(row);
                });

                const seeMoreBtn = profileEl.querySelector('#artistSeeMore');
                if (sortedSongs.length <= maxInitial) {
                    seeMoreBtn.style.display = 'none';
                } else {
                    seeMoreBtn.textContent = showAll ? 'VER MENOS' : 'VER MAS';
                    seeMoreBtn.onclick = () => {
                        showAll = !showAll;
                        renderSongs();
                    };
                }
            }

            renderSongs();

            profileEl.querySelector('#artistPlayAllBtn').addEventListener('click', () => {
                setQueueAndPlayFromSongs(sortedSongs, sortedSongs[0]);
            });

            const playlistView = document.getElementById('playlistView');
            if (!playlistView) return;

            playlistView.innerHTML = '';
            const backBtn = document.createElement('button');
            backBtn.className = 'back-button';
            backBtn.textContent = '<- Volver';
            backBtn.onclick = () => {
                playlistView.style.display = 'none';
                showHomeView();
            };

            playlistView.appendChild(backBtn);
            playlistView.appendChild(profileEl);

            document.getElementById('searchView').style.display = 'none';
            document.getElementById('libraryView').style.display = 'none';
            const homeView = document.getElementById('homeView');
            if (homeView) homeView.style.display = 'none';
            playlistView.style.display = 'block';
        }

        // ========================================
        // EXPORT DEL MÓDULO
        // ========================================
        return {
            loadUserData,               // Carga datos del usuario (favoritos, historial, playlists)
            setupInitialDataLoad,       // Configura carga inicial cuando DOM está listo
            openArtistPage,             // Abre página de artista por nombre
            openAlbumView,              // Abre vista de álbum con ID y metadatos
            loadArtistPage,             // Carga datos del artista desde servidor
            displayAlbumView,           // Renderiza vista de álbum en el DOM
            displayArtistProfile,       // Renderiza perfil completo de artista
        };
    }

    // Expone el módulo globalmente
    window.EsplotifyViews = {
        createViewsModule,
    };
})();
